
#Wards Settings
[Wards]

	#Enchantments
	[Wards.Enchantments]
		#Curse Enchantments
		curseEnchantments = ["minecraft:binding_curse", "minecraft:vanishing_curse", "charm:leeching_curse"]
		#Haste Enchantments
		hasteEnchantments = ["minecraft:efficiency", "minecraft:quick_charge"]
		#Knowledge Enchantments
		knowledgeEnchantments = ["minecraft:infinity", "minecraft:mending", "minecraft:loyalty", "charm:homing", "charm:magnetic", "charm:salvage"]
		#Luck Enchantments
		luckEnchantments = ["minecraft:looting", "minecraft:silk_touch", "minecraft:fortune", "minecraft:luck_of_the_sea", "minecraft:lure"]
		#Destruction Enchantments
		destructionEnchantments = ["minecraft:blast_protection", "minecraft:multishot", "minecraft:sweeping", "minecraft:channeling"]
		#Slayer Enchantments
		slayerEnchantments = ["minecraft:smite", "minecraft:bane_of_arthropods", "minecraft:impaling", "minecraft:piercing"]
		#Combat Enchantments
		combatEnchantments = ["minecraft:lapis_lazuli-10000", "wards:enchanted_paper-15000"]
		#Fortitude Enchantments
		fortitudeEnchantments = ["minecraft:protection", "minecraft:projectile_protection", "minecraft:thorns", "minecraft:unbreaking", "minecraft:feather_falling", "charm:curse_break"]
		#Fire Enchantments
		fireEnchantments = ["minecraft:fire_protection", "minecraft:fire_aspect", "minecraft:flame"]
		#Water Enchantments
		waterEnchantments = ["minecraft:respiration", "minecraft:aqua_affinity", "minecraft:depth_strider", "minecraft:frost_walker"]

	#Items
	[Wards.Items]
		#Power Sources
		powerSources = ["minecraft:lapis_lazuli-10000", "wards:enchanted_paper-15000"]
		#Accepted Items
		acceptedItems = ["minecraft:enchanted_book", "minecraft:book", "quark:ancient_tome"]

